In [1]:
import numpy as np

In [2]:
# Creating a numpy array

a = np.array([1,2,3])

In [3]:
a 

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
list_b = [4,5,6]
b = np.array(list_b)

In [6]:
b

array([4, 5, 6])

In [8]:
# why do we need array when we can use List? 
list_a = [1,2,3]
list_b = [4,5,6]


In [9]:
list_a + list_b # Not what we want 

[1, 2, 3, 4, 5, 6]

In [11]:
# Just to add two numerical list together
sum_list = []
if len(list_a) == len(list_b):
    for i in range(len(list_a)):
        result = list_a[i] + list_b[i]
        sum_list.append(result)
sum_list

[5, 7, 9]

In [13]:
c = a + b # with a numpy array we add 
# with just a line of code and it efficient

In [14]:
c

array([5, 7, 9])

In [16]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [15]:
a > b

array([False, False, False])

In [21]:
d = np.array([1,2,3,4,'Dog'])

In [22]:
e = np.array([1,2,3,4,'Cat'])

In [23]:
d+e

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [24]:
f = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [25]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
f.shape

(3, 3)

In [27]:
a.shape

(3,)

In [28]:
g = np.array([[1,2],
              [3,4]])

In [29]:
g.shape

(2, 2)

In [30]:
g.size

4

In [31]:
f.size

9

In [32]:
h = np.array([[5,6],
              [7,8]])

In [33]:
g*h

array([[ 5, 12],
       [21, 32]])

In [34]:
g.dot(h)

array([[19, 22],
       [43, 50]])

In [35]:
f*g

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [39]:
np.arange(10, 26, 5)

array([10, 15, 20, 25])

In [41]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

In [42]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
g

array([[1, 2],
       [3, 4]])

In [47]:
f[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
np.array([[]])